version: "3.7"
name: lms
services:
    mariadb:
        image: mariadb:10.8
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake
            - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
        environment:
            MYSQL_ROOT_PASSWORD: 123
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - default

    redis:
        image: redis:alpine
        networks:
            - default

    frappe:
        image: frappe/bench:latest
        command: bash /workspace/init.sh
        environment:
            - SHELL=/bin/bash
        working_dir: /home/frappe
        volumes:
            - .:/workspace
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.lms.rule=Host(`lms.ablarsy.com`)"
            - "traefik.http.routers.lms.entrypoints=websecure"
            - "traefik.http.routers.lms.tls=true"
            - "traefik.http.routers.lms.tls.certresolver=mytlschallenge"
            - "traefik.http.services.lms.loadbalancer.server.port=8000"
        networks:
            - default
            - root_default

volumes:
    mariadb-data:

networks:
    root_default:
        external: true
